default_track_label:
  default: "English"
default_track_langcode:
  default: "en"
allowed_groups:
  type: list
  default: ""
  list_type: compact
  description: "Only users in these groups can use the insert video button. Enter group names separated by pipe (|). Leave empty to allow all users."
disable_download:
  type: bool
  default: false
text_tracks_as_blobs:
  default: true
  description: "When using subtitles, download VTT files and inject as blob (fixes issues when using S3 storage or a CDN)"
